# Generated by Django 6.0.5 on 2026-05-09 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_alter_almacen_table_alter_empresa_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idestante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=20)),
                ('alto', models.IntegerField(default=30)),
                ('profundidad', models.IntegerField(default=20)),
                ('lado', models.CharField(choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha')], default='derecha', max_length=10)),
                ('cantidadniveles', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
                'db_table': 'estante',
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idpasillo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=40)),
                ('largo', models.IntegerField(default=60)),
                ('orientacion', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=10)),
            ],
            options={
                'verbose_name': 'Pasillo',
                'verbose_name_plural': 'Pasillos',
                'db_table': 'pasillo',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idnivel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('altura', models.IntegerField(default=10)),
                ('idestante', models.ForeignKey(db_column='idestante', on_delete=django.db.models.deletion.CASCADE, to='layout.estante')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'nivel',
                'unique_together': {('idestante', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='estante',
            name='idpasillo',
            field=models.ForeignKey(db_column='idpasillo', on_delete=django.db.models.deletion.CASCADE, to='layout.pasillo'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idubicacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('capacidadpeso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidadvolumen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_ubicacion', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=15)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('idnivel', models.ForeignKey(db_column='idnivel', on_delete=django.db.models.deletion.CASCADE, to='layout.nivel')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idnodo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('esquina', 'Esquina'), ('interseccion', 'Intersección'), ('punto_recogida', 'Punto de Recogida')], max_length=20)),
                ('coordenada_x', models.IntegerField()),
                ('coordenada_y', models.IntegerField()),
                ('idalmacen', models.ForeignKey(db_column='idalmacen', on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen')),
                ('idubicacion', models.ForeignKey(blank=True, db_column='idubicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='layout.ubicacion')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'db_table': 'nodo',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idzona', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('recepcion', 'Recepción'), ('almacenamiento', 'Almacenamiento'), ('despacho', 'Despacho'), ('picking', 'Picking'), ('devoluciones', 'Devoluciones')], max_length=20)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=100)),
                ('alto', models.IntegerField(default=100)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('idalmacen', models.ForeignKey(db_column='idalmacen', on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zona',
                'unique_together': {('idalmacen', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='pasillo',
            name='idzona',
            field=models.ForeignKey(db_column='idzona', on_delete=django.db.models.deletion.CASCADE, to='layout.zona'),
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idconexion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('pasillo', 'Pasillo'), ('cruce', 'Cruce'), ('acceso', 'Acceso Directo')], default='pasillo', max_length=20)),
                ('bidireccional', models.BooleanField(default=True)),
                ('idnododestino', models.ForeignKey(db_column='idnododestino', on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='layout.nodo')),
                ('idnodoorigen', models.ForeignKey(db_column='idnodoorigen', on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='layout.nodo')),
            ],
            options={
                'verbose_name': 'Conexión',
                'verbose_name_plural': 'Conexiones',
                'db_table': 'conexion',
                'unique_together': {('idnodoorigen', 'idnododestino')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='estante',
            unique_together={('idpasillo', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='pasillo',
            unique_together={('idzona', 'codigo')},
        ),
    ]
