# Generated by Django 6.0.5 on 2026-05-24 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zona',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nodo',
            name='idalmacen',
            field=models.ForeignKey(blank=True, db_column='idalmacen', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen'),
        ),
        migrations.AddField(
            model_name='zona',
            name='idalmacen',
            field=models.ForeignKey(blank=True, db_column='idalmacen', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen'),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='idsucursal',
            field=models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='idsucursal',
            field=models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal'),
        ),
    ]
