# Generated by Django 6.0.5 on 2026-05-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_fix_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
    ]
