# Generated by Django 6.0.5 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_alter_ubicacion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='alto',
            field=models.FloatField(default=80),
        ),
        migrations.AddField(
            model_name='zona',
            name='ancho',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='zona',
            name='es_mascara',
            field=models.BooleanField(default=False, help_text='Indica si es la zona visual de un almacén'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='poligono',
            field=models.JSONField(blank=True, help_text='Forma: {"tipo":"poligono","puntos":[[x,y],...]} o {"tipo":"circulo","centro":[x,y],"radio":r}', null=True),
        ),
    ]
