from typing import Any, Protocol


class ICrudService(Protocol):
    """Contrato base para servicios CRUD."""

    def listar(self, **filtros) -> list[Any]: ...
    def obtener(self, id: str) -> Any: ...
    def crear(self, data: dict) -> Any: ...
    def actualizar(self, id: str, data: dict) -> Any: ...
    def eliminar(self, id: str) -> None: ...
    def toggle_estado(self, id: str) -> bool: ...
