# Generated by Django 6.0.5 on 2026-05-24 03:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idtransferencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_transferencia', models.CharField(max_length=50)),
                ('estado_transferencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('idalmacen_destino', models.ForeignKey(db_column='idalmacen_destino', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='empresa.almacen')),
                ('idalmacen_origen', models.ForeignKey(db_column='idalmacen_origen', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='empresa.almacen')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'db_table': 'transferencia',
                'unique_together': {('idalmacen_origen', 'numero_transferencia')},
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('iddetalletransferencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idlote', models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('idtransferencia', models.ForeignKey(db_column='idtransferencia', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='transferencia.transferencia')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencias',
                'db_table': 'detalletransferencia',
            },
        ),
    ]
