# Generated by Django 6.0.5 on 2026-05-09 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAlmacen',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Almacén',
                'db_table': 'auditoria"."auditoriaalmacen',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpresa',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Empresa',
                'db_table': 'auditoria"."auditoriaempresa',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPermiso',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Permiso',
                'db_table': 'auditoria"."auditoriapermiso',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRol',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Rol',
                'db_table': 'auditoria"."auditoriarol',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRolPermiso',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Rol-Permiso',
                'db_table': 'auditoria"."auditoriarolpermiso',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSesionUsuario',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Sesión Usuario',
                'db_table': 'auditoria"."auditoriancesionusuario',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSucursal',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Sucursal',
                'db_table': 'auditoria"."auditoriasucursal',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Usuario',
                'db_table': 'auditoria"."auditoriausuario',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuarioRol',
            fields=[
                ('idauditoria', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('idregistro', models.UUIDField()),
                ('idusuario', models.UUIDField(blank=True, null=True)),
                ('tipooperacion', models.CharField(max_length=10)),
                ('datosanteriores', models.JSONField(blank=True, null=True)),
                ('datosnuevos', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaevento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría Usuario-Rol',
                'db_table': 'auditoria"."auditoriausuariorol',
            },
        ),
    ]
