# Generated by Django 6.0.5 on 2026-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditoria_habilitada', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'db_table': 'config_auditoria',
            },
        ),
    ]
