# Generated by Django 6.0.5 on 2026-05-09 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idempresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razonsocial', models.CharField(max_length=200)),
                ('nombrecomercial', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idsucursal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idempresa', models.ForeignKey(db_column='idempresa', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'unique_together': {('idempresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idalmacen', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidadmaxima', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idsucursal', models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
                'unique_together': {('idsucursal', 'codigo')},
            },
        ),
    ]
