# Generated by Django 6.0.5 on 2026-05-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='almacen',
            table='almacen',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
    ]
