# Generated by Django 6.0.5 on 2026-05-09 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_alter_almacen_table_alter_empresa_table_and_more'),
        ('inventario', '0001_initial'),
        ('layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePicking',
            fields=[
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('iddetallepicking', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_pickeada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('incidencia', 'Con Incidencia')], default='pendiente', max_length=20)),
                ('idlote', models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('idubicacion', models.ForeignKey(db_column='idubicacion', on_delete=django.db.models.deletion.CASCADE, to='layout.ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle de Picking',
                'verbose_name_plural': 'Detalles de Picking',
                'db_table': 'detallepicking',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idincidencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('faltante', 'Faltante'), ('danado', 'Dañado'), ('caducado', 'Caducado'), ('ubicacion_vacia', 'Ubicación Vacía'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('cantidad_reportada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('iddetalle', models.ForeignKey(db_column='iddetalle', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='picking.detallepicking')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
            },
        ),
        migrations.CreateModel(
            name='OrdenPicking',
            fields=[
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idordenpicking', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('idalmacen', models.ForeignKey(db_column='idalmacen', on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Picking',
                'verbose_name_plural': 'Órdenes de Picking',
                'db_table': 'ordenpicking',
            },
        ),
        migrations.AddField(
            model_name='detallepicking',
            name='idorden',
            field=models.ForeignKey(db_column='idorden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='picking.ordenpicking'),
        ),
    ]
