# Generated by Django 6.0.5 on 2026-05-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('picking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenpicking',
            name='idalmacen',
            field=models.ForeignKey(db_column='idalmacen', on_delete=django.db.models.deletion.CASCADE, to='empresa.almacen'),
        ),
        migrations.AddField(
            model_name='ordenpicking',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepicking',
            name='idorden',
            field=models.ForeignKey(db_column='idorden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='picking.ordenpicking'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenpicking',
            unique_together={('idalmacen', 'numero_orden')},
        ),
    ]
