from django.urls import path
from portal.controllers.auditoria.views import (
    AuditoriaEmpresaViewSet,
    AuditoriaSucursalViewSet,
    AuditoriaAlmacenViewSet,
    AuditoriaUsuarioViewSet,
    AuditoriaRolViewSet,
    AuditoriaPermisoViewSet,
    AuditoriaUsuarioRolViewSet,
    AuditoriaRolPermisoViewSet,
    AuditoriaSesionUsuarioViewSet,
    AuditoriaCategoriaViewSet,
    AuditoriaProductoViewSet,
    AuditoriaLoteViewSet,
    AuditoriaInventarioViewSet,
    AuditoriaKardexViewSet,
    AuditoriaZonaViewSet,
    AuditoriaEstanteViewSet,
    AuditoriaNivelViewSet,
    AuditoriaUbicacionViewSet,
    AuditoriaNodoViewSet,
    AuditoriaConexionViewSet,
    AuditoriaOrdenPickingViewSet,
    AuditoriaDetallePickingViewSet,
    AuditoriaIncidenciaViewSet,
    AuditoriaTransferenciaViewSet,
    AuditoriaDetalleTransferenciaViewSet,
)

urlpatterns = [
    path('empresa/<uuid:idempresa>/empresas/', AuditoriaEmpresaViewSet.as_view({'get': 'list'}), name='aud-empresa'),
    path('empresa/<uuid:idempresa>/sucursales/', AuditoriaSucursalViewSet.as_view({'get': 'list'}), name='aud-sucursal'),
    path('empresa/<uuid:idempresa>/almacenes/', AuditoriaAlmacenViewSet.as_view({'get': 'list'}), name='aud-almacen'),
    path('empresa/<uuid:idempresa>/usuarios/', AuditoriaUsuarioViewSet.as_view({'get': 'list'}), name='aud-usuario'),
    path('empresa/<uuid:idempresa>/roles/', AuditoriaRolViewSet.as_view({'get': 'list'}), name='aud-rol'),
    path('empresa/<uuid:idempresa>/permisos/', AuditoriaPermisoViewSet.as_view({'get': 'list'}), name='aud-permiso'),
    path('empresa/<uuid:idempresa>/usuariorol/', AuditoriaUsuarioRolViewSet.as_view({'get': 'list'}), name='aud-usuariorol'),
    path('empresa/<uuid:idempresa>/rolpermiso/', AuditoriaRolPermisoViewSet.as_view({'get': 'list'}), name='aud-rolpermiso'),
    path('empresa/<uuid:idempresa>/sesiones/', AuditoriaSesionUsuarioViewSet.as_view({'get': 'list'}), name='aud-sesion'),
    path('empresa/<uuid:idempresa>/categorias/', AuditoriaCategoriaViewSet.as_view({'get': 'list'}), name='aud-categoria'),
    path('empresa/<uuid:idempresa>/productos/', AuditoriaProductoViewSet.as_view({'get': 'list'}), name='aud-producto'),
    path('empresa/<uuid:idempresa>/lotes/', AuditoriaLoteViewSet.as_view({'get': 'list'}), name='aud-lote'),
    path('empresa/<uuid:idempresa>/inventario/', AuditoriaInventarioViewSet.as_view({'get': 'list'}), name='aud-inventario'),
    path('empresa/<uuid:idempresa>/kardex/', AuditoriaKardexViewSet.as_view({'get': 'list'}), name='aud-kardex'),
    path('empresa/<uuid:idempresa>/zonas/', AuditoriaZonaViewSet.as_view({'get': 'list'}), name='aud-zona'),
    path('empresa/<uuid:idempresa>/estantes/', AuditoriaEstanteViewSet.as_view({'get': 'list'}), name='aud-estante'),
    path('empresa/<uuid:idempresa>/niveles/', AuditoriaNivelViewSet.as_view({'get': 'list'}), name='aud-nivel'),
    path('empresa/<uuid:idempresa>/ubicaciones/', AuditoriaUbicacionViewSet.as_view({'get': 'list'}), name='aud-ubicacion'),
    path('empresa/<uuid:idempresa>/nodos/', AuditoriaNodoViewSet.as_view({'get': 'list'}), name='aud-nodo'),
    path('empresa/<uuid:idempresa>/conexiones/', AuditoriaConexionViewSet.as_view({'get': 'list'}), name='aud-conexion'),
    path('empresa/<uuid:idempresa>/ordenes-picking/', AuditoriaOrdenPickingViewSet.as_view({'get': 'list'}), name='aud-ordenpicking'),
    path('empresa/<uuid:idempresa>/detalles-picking/', AuditoriaDetallePickingViewSet.as_view({'get': 'list'}), name='aud-detallepicking'),
    path('empresa/<uuid:idempresa>/incidencias/', AuditoriaIncidenciaViewSet.as_view({'get': 'list'}), name='aud-incidencia'),
    path('empresa/<uuid:idempresa>/transferencias/', AuditoriaTransferenciaViewSet.as_view({'get': 'list'}), name='aud-transferencia'),
    path('empresa/<uuid:idempresa>/detalles-transferencia/', AuditoriaDetalleTransferenciaViewSet.as_view({'get': 'list'}), name='aud-detalletransferencia'),
]
