from django.urls import path
from portal.controllers.auditoria.views import (
    AuditoriaEmpresaViewSet, AuditoriaSucursalViewSet, AuditoriaAlmacenViewSet,
    AuditoriaUsuarioViewSet, AuditoriaRolViewSet, AuditoriaPermisoViewSet,
    AuditoriaUsuarioRolViewSet, AuditoriaRolPermisoViewSet, AuditoriaSesionUsuarioViewSet,
    AuditoriaCategoriaViewSet, AuditoriaProductoViewSet, AuditoriaLoteViewSet,
    AuditoriaInventarioViewSet, AuditoriaKardexViewSet,
    AuditoriaZonaViewSet, AuditoriaEstanteViewSet,
    AuditoriaNivelViewSet, AuditoriaUbicacionViewSet, AuditoriaNodoViewSet, AuditoriaConexionViewSet,
    AuditoriaOrdenPickingViewSet, AuditoriaDetallePickingViewSet, AuditoriaIncidenciaViewSet,
    AuditoriaTransferenciaViewSet, AuditoriaDetalleTransferenciaViewSet,
)

urlpatterns = [
    path('<uuid:idempresa>/empresas/', AuditoriaEmpresaViewSet.as_view({'get': 'list'}), name='aud-empresa'),
    path('<uuid:idempresa>/sucursales/', AuditoriaSucursalViewSet.as_view({'get': 'list'}), name='aud-sucursal'),
    path('<uuid:idempresa>/almacenes/', AuditoriaAlmacenViewSet.as_view({'get': 'list'}), name='aud-almacen'),
    path('<uuid:idempresa>/usuarios/', AuditoriaUsuarioViewSet.as_view({'get': 'list'}), name='aud-usuario'),
    path('<uuid:idempresa>/roles/', AuditoriaRolViewSet.as_view({'get': 'list'}), name='aud-rol'),
    path('<uuid:idempresa>/permisos/', AuditoriaPermisoViewSet.as_view({'get': 'list'}), name='aud-permiso'),
    path('<uuid:idempresa>/usuariorol/', AuditoriaUsuarioRolViewSet.as_view({'get': 'list'}), name='aud-usuariorol'),
    path('<uuid:idempresa>/rolpermiso/', AuditoriaRolPermisoViewSet.as_view({'get': 'list'}), name='aud-rolpermiso'),
    path('<uuid:idempresa>/sesiones/', AuditoriaSesionUsuarioViewSet.as_view({'get': 'list'}), name='aud-sesion'),
    path('<uuid:idempresa>/categorias/', AuditoriaCategoriaViewSet.as_view({'get': 'list'}), name='aud-categoria'),
    path('<uuid:idempresa>/productos/', AuditoriaProductoViewSet.as_view({'get': 'list'}), name='aud-producto'),
    path('<uuid:idempresa>/lotes/', AuditoriaLoteViewSet.as_view({'get': 'list'}), name='aud-lote'),
    path('<uuid:idempresa>/inventario/', AuditoriaInventarioViewSet.as_view({'get': 'list'}), name='aud-inventario'),
    path('<uuid:idempresa>/kardex/', AuditoriaKardexViewSet.as_view({'get': 'list'}), name='aud-kardex'),
    path('<uuid:idempresa>/zonas/', AuditoriaZonaViewSet.as_view({'get': 'list'}), name='aud-zona'),
    path('<uuid:idempresa>/estantes/', AuditoriaEstanteViewSet.as_view({'get': 'list'}), name='aud-estante'),
    path('<uuid:idempresa>/niveles/', AuditoriaNivelViewSet.as_view({'get': 'list'}), name='aud-nivel'),
    path('<uuid:idempresa>/ubicaciones/', AuditoriaUbicacionViewSet.as_view({'get': 'list'}), name='aud-ubicacion'),
    path('<uuid:idempresa>/nodos/', AuditoriaNodoViewSet.as_view({'get': 'list'}), name='aud-nodo'),
    path('<uuid:idempresa>/conexiones/', AuditoriaConexionViewSet.as_view({'get': 'list'}), name='aud-conexion'),
    path('<uuid:idempresa>/ordenes-picking/', AuditoriaOrdenPickingViewSet.as_view({'get': 'list'}), name='aud-ordenpicking'),
    path('<uuid:idempresa>/detalles-picking/', AuditoriaDetallePickingViewSet.as_view({'get': 'list'}), name='aud-detallepicking'),
    path('<uuid:idempresa>/incidencias/', AuditoriaIncidenciaViewSet.as_view({'get': 'list'}), name='aud-incidencia'),
    path('<uuid:idempresa>/transferencias/', AuditoriaTransferenciaViewSet.as_view({'get': 'list'}), name='aud-transferencia'),
    path('<uuid:idempresa>/detalles-transferencia/', AuditoriaDetalleTransferenciaViewSet.as_view({'get': 'list'}), name='aud-detalletransferencia'),
]
