# Generated by Django 6.0.5 on 2026-05-09 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idcategoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idcategoriapadre', models.ForeignKey(blank=True, db_column='idcategoriapadre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idproducto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('caja', 'Caja'), ('pallet', 'Pallet')], default='unidad', max_length=20)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maneja_lotes', models.BooleanField(default=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idcategoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idlote', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lote',
                'unique_together': {('idproducto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idkardex', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('idubicacion', models.ForeignKey(blank=True, db_column='idubicacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='layout.ubicacion')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idlote', models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'db_table': 'kardex',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idinventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ultimo_conteo', models.DateTimeField(auto_now=True)),
                ('idubicacion', models.ForeignKey(db_column='idubicacion', on_delete=django.db.models.deletion.CASCADE, to='layout.ubicacion')),
                ('idlote', models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'unique_together': {('idproducto', 'idlote', 'idubicacion')},
            },
        ),
    ]
