# Generated by Django 6.0.5 on 2026-05-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kardex',
            name='idlote',
            field=models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='idlote',
            field=models.ForeignKey(blank=True, db_column='idlote', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idcategoria',
            field=models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AddField(
            model_name='lote',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('idempresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('idcategoria', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('idproducto', 'numero_lote')},
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('idproducto', 'idlote', 'idubicacion')},
        ),
    ]
