# Generated by Django 6.0.5 on 2026-05-09 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idpermiso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idrol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idusuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimologin', models.DateTimeField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('idempresa', models.ForeignKey(blank=True, db_column='idempresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idsesionusuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokenjwt', models.TextField()),
                ('refreshtoken', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('fechainicio', models.DateTimeField(auto_now_add=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
                'db_table': 'sesionusuario',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idrolpermiso', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idpermiso', models.ForeignKey(db_column='idpermiso', on_delete=django.db.models.deletion.CASCADE, to='seguridad.permiso')),
                ('idrol', models.ForeignKey(db_column='idrol', on_delete=django.db.models.deletion.CASCADE, to='seguridad.rol')),
            ],
            options={
                'verbose_name': 'Rol - Permiso',
                'verbose_name_plural': 'Roles - Permisos',
                'db_table': 'rolpermiso',
                'unique_together': {('idrol', 'idpermiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('idultimaauditoria', models.UUIDField(blank=True, null=True)),
                ('idusuariorol', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idrol', models.ForeignKey(db_column='idrol', on_delete=django.db.models.deletion.CASCADE, to='seguridad.rol')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario - Rol',
                'verbose_name_plural': 'Usuarios - Roles',
                'db_table': 'usuariorol',
                'unique_together': {('idusuario', 'idrol')},
            },
        ),
    ]
