# Generated by Django 6.0.5 on 2026-05-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionusuario',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
