# Generated by Django 6.0.5 on 2026-05-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table='permiso',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='rolpermiso',
        ),
        migrations.AlterModelTable(
            name='sesionusuario',
            table='sesionusuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuariorol',
        ),
    ]
