# Generated by Django 6.0.5 on 2026-05-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("SELECT 1", "SELECT 1"),
    ]
