# Generated by Django 5.0.6 on 2026-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_permiso_table_alter_rol_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_sistema', 'Administrador SIPRO'), ('admin_empresa', 'Administrador de Empresa'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
