# Generated by Django 6.0.5 on 2026-05-24 04:24

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_sesionusuario_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionusuario',
            name='refreshtoken',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionusuario',
            name='tokenjwt',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
