from abc import ABC, abstractmethod
import uuid

class IEmpresaRepository(ABC):
    @abstractmethod
    def get_all(self) -> list: ...
    @abstractmethod
    def get_by_id(self, idempresa: uuid.UUID): ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idempresa: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idempresa: uuid.UUID): ...
    @abstractmethod
    def toggle_estado(self, idempresa: uuid.UUID) -> bool: ...

class ISucursalRepository(ABC):
    @abstractmethod
    def get_all(self, idempresa: uuid.UUID | None = None) -> list: ...
    @abstractmethod
    def get_by_id(self, idsucursal: uuid.UUID): ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idsucursal: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idsucursal: uuid.UUID): ...
    @abstractmethod
    def toggle_estado(self, idsucursal: uuid.UUID) -> bool: ...
    @abstractmethod
    def get_by_empresa(self, idempresa: uuid.UUID) -> list: ...

class IAlmacenRepository(ABC):
    @abstractmethod
    def get_all(self, idsucursal: uuid.UUID | None = None) -> list: ...
    @abstractmethod
    def get_by_id(self, idalmacen: uuid.UUID): ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idalmacen: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idalmacen: uuid.UUID): ...
    @abstractmethod
    def toggle_estado(self, idalmacen: uuid.UUID) -> bool: ...
    @abstractmethod
    def get_by_sucursal(self, idsucursal: uuid.UUID) -> list: ...
