from abc import ABC, abstractmethod
import uuid

class ICategoriaRepository(ABC):
    @abstractmethod
    def get_all(self) -> list: ...
    @abstractmethod
    def get_raices(self) -> list: ...
    @abstractmethod
    def get_by_id(self, idcategoria: uuid.UUID): ...
    @abstractmethod
    def get_subcategorias(self, idcategoria: uuid.UUID) -> list: ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idcategoria: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idcategoria: uuid.UUID): ...
    @abstractmethod
    def toggle_estado(self, idcategoria: uuid.UUID) -> bool: ...

class IProductoRepository(ABC):
    @abstractmethod
    def get_all(self, idcategoria: uuid.UUID | None = None, search: str | None = None) -> list: ...
    @abstractmethod
    def get_by_id(self, idproducto: uuid.UUID): ...
    @abstractmethod
    def get_lotes(self, idproducto: uuid.UUID) -> list: ...
    @abstractmethod
    def get_inventario(self, idproducto: uuid.UUID) -> list: ...
    @abstractmethod
    def get_kardex(self, idproducto: uuid.UUID) -> list: ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idproducto: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idproducto: uuid.UUID): ...

class IInventarioRepository(ABC):
    @abstractmethod
    def get_all(self, idproducto: uuid.UUID | None = None, idubicacion: uuid.UUID | None = None) -> list: ...
    @abstractmethod
    def get_disponible_para_picking(self, producto_id: uuid.UUID, estrategia: str = 'fefo') -> list: ...
