from abc import ABC, abstractmethod
import uuid

class ITransferenciaRepository(ABC):
    @abstractmethod
    def get_all(self) -> list: ...
    @abstractmethod
    def get_by_id(self, idtransferencia: uuid.UUID): ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, idtransferencia: uuid.UUID, data: dict): ...
    @abstractmethod
    def delete(self, idtransferencia: uuid.UUID): ...
    @abstractmethod
    def cambiar_estado(self, idtransferencia: uuid.UUID, estado: str): ...
    @abstractmethod
    def get_detalles(self, idtransferencia: uuid.UUID) -> list: ...
